# Generated by Django 4.2.5 on 2023-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_ORMapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.PositiveIntegerField(),
        ),
    ]
