# Generated by Django 4.2.5 on 2023-10-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz_ORMapp', '0002_alter_client_tel'),
        ('dz_ORMapp', '0003_product_foto_alter_client_tel'),
    ]

    operations = [
    ]
